PROJNAME=Modulio_LPS25H_27143
DEVICE=CY8C27143B
BASEDEVICE=CY8C27100B
PROJPATH=Z:/TMP/Modulio/Proj/V8/PSoC1/MODU~4E8/MODU~4E8
PSOCDIR=C:/PROGRA~1/Cypress/PSOCDE~1/5.4/Common/CY3E64~1
INCLUDE_PATH=C:/PROGRA~1/Cypress/PSOCDE~1/5.4/Common/CY3E64~1/tools/include/CY8C27~1
CSRCS= ..\..\lib_modulio\acm1602.c ..\..\lib_modulio\lps25h.c ..\..\lib_modulio\modulio_common.c ..\..\lib_modulio\modulio_hal.c main.c
LIBCSRCS=
STDCSRCS=
ASMSRCS= ..\..\lib_modulio\psoc1_delay.asm
LIBASMSRCS= i2chw_1common.asm i2chw_1int.asm i2chw_1mstr.asm i2chw_1rsrcinits.asm psocconfig.asm psocconfigtbl.asm
STDASMSRCS=
OBJECT_SOURCES= ..\..\lib_modulio\acm1602.c ..\..\lib_modulio\lps25h.c ..\..\lib_modulio\modulio_common.c ..\..\lib_modulio\modulio_hal.c ..\..\lib_modulio\psoc1_delay.asm main.c
FILLVALUE=0x30
LASTROM=0x3fff
LASTRAM=0xff
CODECOMPRESSOR=
MORE_CFLAGS=-Wf-Osize 
RELSTART=0x1a0
INC_PATH= Z:\TMP\Modulio\Proj\V6\PSoC1 Z:\TMP\Modulio\Proj\V6\PSoC1\Lib_Modulio
CDEFINES=
LIBS=
UMLIBS=
LIB_PATH=
ENABLE_ALIGN_SHIFT=0
LMM=
SYS_INC_CONTENTS:=SYSTEM_STACK_PAGE:_equ_0 SYSTEM_STACK_BASE_ADDR:_equ_0h SYSTEM_LARGE_MEMORY_MODEL:_equ_0 SYSTEM_SMALL_MEMORY_MODEL:_equ_1 IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_IMAGECRAFT 
SYSTEM_TOOLS=1
CSFLOW=
CONFIG_NAMES=modulio_lps25h 
